redis_url = "redis://:AtSeeDFtZvFkYFwSPbZVDMx3@localhost:6380/0"

[[nodes]]
node_name = "tick"
node_class = "tick"


[[nodes]]
node_name = "performance"
node_class = "performance"


[nodes.node_args]
input_channel = "tick/secs/1"
output_channel = "performance"
message_size = 10
