extra_modules = ["teleop.vr_controller_node", "teleop.data_classes"]
redis_url = "redis://172.26.121.171:6379/0"

# GCP redis
# redis_url = "redis://35.236.217.22:6379/0"


[[nodes]]
node_name = "quest_3_controller"
node_class = "quest_controller"

[nodes.node_args]
input_channel = "stretch_status"
output_channel = "quest_control"
translation_speed = 20
quest_controller_ip = "172.26.172.110"


# [[nodes]]
# node_name = "human_speaker"
# node_class = "speaker"

# [nodes.node_args]
# input_channel = "audio_output"

# [nodes.node_args.interrupt_channel_types]
# intermediate_transcription = "text"



# [[nodes]]
# node_name = "listener"
# node_class = "listener"

# [nodes.node_args]
# output_channel = "computer_audio_input"

# [[nodes]]
# node_name = "transcriber"
# node_class = "transcriber"

# [nodes.node_args]
# input_channel = "computer_audio_input"
# final_output_channel = "task_output"
# intermediate_output_channel = "mid_task_output"
# rate = 44100


# [[nodes]]
# node_name = "record"
# node_class = "record"


# [nodes.node_args]
# jsonl_file_path = "record.jsonl"

# [nodes.node_args.record_channel_types]
# "stretch_status" = "target_position"
# "quest_control" = "target_position"
# "audio_input" = "audio"
# "meta_2_head_cam" = "image"
# "task_output" = "text"
# "wrist_cam" = "image"
