extra_modules = ["teleop.vr_controller_node", "teleop.data_classes"]
redis_url = "redis://<your_redis_url>:6379/0"


[[nodes]]
node_name = "quest_3_controller"
node_class = "quest_controller"

[nodes.node_args]
input_channel = "stretch_status"
output_channel = "quest_control"
translation_speed = 20
quest_controller_ip = "172.26.172.110"
