[[nodes]]
node_name = "speaker"
node_class = "speaker"
run_in_subprocess = true

[nodes.node_args]
input_channel = "audio_input"

[[nodes]]
node_name = "listener"
node_class = "listener"
run_in_subprocess = true

[nodes.node_args]
output_channel = "audio_input"
