extra_modules = ["teleop"]

[[nodes]]
node_name = "tick"

[[nodes]]
node_name = "gopro"
output_channel = "wrist_cam"

[[nodes]]
node_name = "webcam"
output_channel = "head_cam"
webcam_id = 6

[[nodes]]
node_name = "stretch"
input_channel = "quest_control"
output_channel = "stretch_status"
