extra_modules = ["teleop.vr_controller_node", "teleop.data_classes"]

[[nodes]]
node_name = "quest_controller"

[nodes.node_args]
input_channel = "stretch_status"
output_channel = "quest_control"
translation_speed = 10

[[nodes]]
node_name = "record"
run_in_subprocess = true

[nodes.node_args]
json_file_path = "record.jsonl"

[nodes.node_args.record_channel_types]
"stretch_status" = "target_position"
"quest_control" = "target_position"
"head_cam" = "image"
"wrist_cam" = "image"
