extra_modules = ["teleop.vr_controller_node", "teleop.data_classes"]
redis_url = "redis://localhost:6379/0"
quest_controller_ip = ""


[[nodes]]
node_name = "quest_controller"
node_class = "quest_controller"

[nodes.node_args]
input_channel = "stretch_status"
output_channel = "quest_control"
translation_speed = 10
